### ISSUE TITLE
some client sided command

### ISSUE THREAD

**Issue by mroep** [coltonk9043/Aoba-MC-Hacked-Client#13]
can you add vclip? or any other command and can you make it so you can change the command prefix to any

**Comment by coltonk9043** [comment]
Yeah! Look forward to it soon.

**Comment by coltonk9043** [comment]
To clarify, by command prefix, you mean ".aoba" right?

**Comment by coltonk9043** [comment]
Closing issue as all features should have been implemented. Let me know if you have any other issues!
