### ISSUE TITLE
Please rework the GUI it just looks on the first look like a wurst skid xd

### ISSUE THREAD

**Issue by Satanaelcode** [coltonk9043/Aoba-MC-Hacked-Client#20]
no joke just overwork the gui and hud to idk use a custom font thats like 3 seconds of work and it would look 10x better just get creative

**Comment by coltonk9043** [comment]
troll

**Comment by OsakiTsukiko** [comment]
2 issues by 2 different acc in the span of 1 min :skull: getting crowded

**Comment by coltonk9043** [comment]
The intention is to look like early similar to Nodus clients. If you want to put the effort in to reworking it, contribute.

**Comment by OsakiTsukiko** [comment]
@coltonk9043 random, but whats a good resource for learning about gl calls (making uis) in fabric (btw, pls check ur mail :skull:)

**Comment by coltonk9043** [comment]
> @coltonk9043 random, but whats a good resource for learning about gl calls (making uis) in fabric (btw, pls check ur mail :skull:)

Sent a reply! Sorry!

**Comment by coltonk9043** [comment]
After over-reacting about your comments on the UI, I gave it some thought and realized that you're right. I'm sorry for the attitude. I'm going to be giving my best attempt to rework the UI over the next week or so and hopefully implement custom font options. Looking forward to any more feedback as it genuinely helps me strive to make the client better. Thanks!

**Comment by OsakiTsukiko** [comment]
I looked a bit through it and I was wondering, whats the point of being able to pin categories and why have UI stuff inside the click gui? Why not go the meteor route where they have 2 different screens for click gui categories and hud editor and then have the in game rendering of whats selected in the hud editor.

**Comment by coltonk9043** [comment]
I like the idea, and will probably go that route. Originally, I only added pins because they are all on the same UI. For now, I think the main focus should be aesthetics but I will for sure start on that once those are done!

**Comment by OsakiTsukiko** [comment]
this would also allow for per module screens (instead of drop down menus) as to not clog the module list with settings
![image](https://github.com/coltonk9043/Aoba-MC-Hacked-Client/assets/104794884/bfeeff1b-f930-4ec5-b0df-e9b676a56d85)
