### ISSUE TITLE
Bro the license CC1.0 wtf you are talking about

### ISSUE THREAD

**Issue by AlexanderMaxRanabel** [coltonk9043/Aoba-MC-Hacked-Client#21]

**Comment by OsakiTsukiko** [comment]
yea... that is a bit weird

**Comment by OsakiTsukiko** [comment]
oh, gpl, thats a decent one, but I don't think that's how ur supposed to declare it :))
(make a LICENSE file containing the license https://choosealicense.com/licenses/gpl-3.0/)

![image](https://github.com/coltonk9043/Aoba-MC-Hacked-Client/assets/104794884/d86e76c4-2764-4590-aa96-29a2a3faee43)

**Comment by coltonk9043** [comment]
The ORIGINAL repo for this was made like 6 years ago when I was still in high school and had no clue about any sort of licensing. I just never bothered changing it.

**Comment by coltonk9043** [comment]
Fixed. Lmk if you find any other issues. :)
