### ISSUE TITLE
dis

### ISSUE THREAD

**Issue by GhostMikz** [coltonk9043/Aoba-MC-Hacked-Client#25]
Hi would you like to create a discord server?
i'd like to suggest some things

**Comment by coltonk9043** [comment]
I was thinking about it! I'll likely get one set up tonight!

**Comment by GhostMikz** [comment]
Great! leave the link when you set it up

**Comment by coltonk9043** [comment]
Half a year later and I finally set up that discord. Here is the link!
https://discord.gg/CceRVcTxpQ
