### ISSUE TITLE
Love it!

### ISSUE THREAD

**Issue by GhostMikz** [coltonk9043/Aoba-MC-Hacked-Client#26]
Nice client i like it but there is a few issues 

It would be nice to add a nametag feature (Similar to meteor client)
And hitbox because some anticheats can detect others hacks but can't detect hitbox
and make HUD togle like turn it on and off it would be so nice

**Comment by coltonk9043** [comment]
Thanks for the suggestions! I'll add these in as soon as I get a chance. Right now I am currently working on the UI overhaul so expect these features to come out once that is finished!
