### ISSUE TITLE
ClickGUI not open 1.20.1

### ISSUE THREAD

**Issue by ekdhedibdsksjwbdjd292857** [coltonk9043/Aoba-MC-Hacked-Client#28]
ClickGUI not opening in 1.20.1
how to open it?

**Comment by coltonk9043** [comment]
Are you pressing the tilda (~) key? If you are, I am not sure what could be going wrong. If you could send me the latest log file (found in %appdata%/.minecraft/logs/latest.log), I might be able to help more.

**Comment by coltonk9043** [comment]
Don't know if you found a solution but try pressing Shift + Tilda (~) together.

**Comment by pmavro** [comment]
for me its there bc the cursor thingy shows up and the keybinds work, however the GUI never shows

**Comment by coltonk9043** [comment]
> for me its there bc the cursor thingy shows up and the keybinds work, however the GUI never shows

Super weird. What is your screen resolution and GUI scale?

**Comment by coltonk9043** [comment]
Found the issue and will be fixed in the next update.
