### ISSUE TITLE
Compatibility.

### ISSUE THREAD

**Issue by impresson** [coltonk9043/Aoba-MC-Hacked-Client#29]
I use this client for compatibility. It is compatible with meteor. I use it as a side client. I think it would be better if you set the default prefix to "-"

**Comment by coltonk9043** [comment]
Once I get off of my ass and finish this UI update, it will allow you to be able to change the prefix to whatever you would like. Hoping to be able to work on it more as I have a little bit of free time in my personal life.

**Comment by coltonk9043** [comment]
![image](https://github.com/coltonk9043/Aoba-MC-Hacked-Client/assets/56643581/2ec394a0-3077-49e3-9dbb-6e7349463587)

Added. It will be available in the next update. Not projected release at the moment.

**Comment by impresson** [comment]
Thanks I hope I can help contribute when I learn to code well lol.

**Comment by impresson** [comment]
Also is there a binding system?

**Comment by coltonk9043** [comment]
Technically yes, but right now there is no way to change them.

**Comment by impresson** [comment]
> Technically yes, but right now there is no way to change them.

Lol

**Comment by coltonk9043** [comment]
Closing issue. The new preview release allows you to change bindings as well.
