### ISSUE TITLE
The chat and gui is mess up

### ISSUE THREAD

**Issue by CrazyH2** [coltonk9043/Aoba-MC-Hacked-Client#30]
When using this the gui is really small like 50% of my screen and the chat messages have no color and have a weird characters everywhere. The gui also doesn't work and I can't press the ~ key as i have to press shift to do it please let us change the key bind!

**Comment by coltonk9043** [comment]
I really have no clue what could be causing the graphical issues. I've seen a few screenshots of other people having issues but haven't been able to replicate it at all. If you can, let me know your screen resolution, java version, and gpu driver version (and which card you use). Hopefully then I might be able to find the cause of it. 

Keybinds are coming soon as well. Been trying my best to keep up with this project to improve it. The foundation for the update is coming along great.

**Comment by coltonk9043** [comment]
Fixed and coming in the next update.
