### ISSUE TITLE
Potential helper?!?!?

### ISSUE THREAD

**Issue by impresson** [coltonk9043/Aoba-MC-Hacked-Client#33]
Hi,
I just wanna see if you would need help developing this client. I like the function of how it works. I just don't seem to understand most parts. I'm no java expert. But I want to become one. My discord is @theofficalpigeon. If you need help just maintaining the project I would be happy to help and learn

**Comment by coltonk9043** [comment]
Hey! I planned to open a discord (which I never got to) that people would be able to join to discuss the client. In terms of a helper, you can contribute by cloning the repo and submitting a pull request with any changes you have made. I'll send the discord here as well as create a new issue that contains a link. Thanks for your interest in the client, I would appreciate any help :)

Link: https://discord.gg/CceRVcTxpQ
