### ISSUE TITLE
Possible compat for Sinytra connector to be used for forge modpacks 1.20.1?

### ISSUE THREAD

**Issue by loweluis** [coltonk9043/Aoba-MC-Hacked-Client#35]
I am using the Sinytra connector to load fabric mods to forge modpacks so I can have the best of both worlds, however I have some issues with this mod in particular, it seems to not work together with the connector. Other fabric mods work just fine I don't really know whats causing the issue to be honest.

The issue is this:
[17:08:47] [WARN] [FabricLoader/Metadata]: Mod aoba uses the version 1.3A which isn't compatible with Loader's extended semantic version format (Could not parse version number component '3A'!), SemVer is recommended for reliably evaluating dependencies and prioritizing newer version

**Comment by coltonk9043** [comment]
Luckily seems like an easy fix. I'll get that fixed when I get home from work today.

**Comment by loweluis** [comment]
Thanks for the quick reply and for the awesome mod, looking forward to the new update

**Comment by coltonk9043** [comment]
Thank you! I should have fixed the problem and it will be out with the next prerelease version. Hope to release that in the next couple of weeks.

**Comment by coltonk9043** [comment]
Just following up, are you still playing in 1.20.1? [Pre-release 2 of 1.4.0](https://github.com/coltonk9043/Aoba-MC-Hacked-Client/releases/tag/v1.4.0-2) should have fixed this issue but I'm fairly certain only works in 1.20.2. If you need 1.20.1, I can backport it to 1.20.1.

**Comment by loweluis** [comment]
> Just following up, are you still playing in 1.20.1? [Pre-release 2 of 1.4.0](https://github.com/coltonk9043/Aoba-MC-Hacked-Client/releases/tag/v1.4.0-2) should have fixed this issue but I'm fairly certain only works in 1.20.2. If you need 1.20.1, I can backport it to 1.20.1.

Yes im still playing 1.20.1 since some mods haven't updated to 1.20.2 yet, I would appreciate if you can update the 1.20.1 version too, thanks

**Comment by cvs0** [comment]
closing as it is inactive.
