### ISSUE TITLE
.


### ISSUE THREAD

**Issue by XD4sty** [coltonk9043/Aoba-MC-Hacked-Client#37]
.

**Comment by coltonk9043** [comment]
Yeah, I understand. My main hurdle is that I honestly don't play Minecraft much if at all anymore, so I rarely get the opportunity to try to client across different servers, anticheats, and modes. That being said, I will still try to tackle this problem to improve the client. Thanks for letting me know!

**Comment by OsakiTsukiko** [comment]
the main rendering loop is per frame, right? maybe add another loop per tick for more intensive checks
