### ISSUE TITLE
Basic Flight Pathind

### ISSUE THREAD

**Issue by kittenvr** [coltonk9043/Aoba-MC-Hacked-Client#45]
could you make a basic flight pathinder that goes to build height using flight looks at the coords put in the module settings and holds w until it gets there optional xaero waypoints list

**Comment by kittenvr** [comment]
this might be usefull https://github.com/MeteorDevelopment/meteor-client/blob/master/src/main/java/meteordevelopment/meteorclient/commands/commands/RotationCommand.java

**Comment by kittenvr** [comment]
xaero thing might be easier with xaeroplus since opensrouce

**Comment by coltonk9043** [comment]
That should be really easy to do. I will work on that within the next couple of days. 

I will try to incorporate some more complex pathfinding so it doesn't necessarily need to use flight, and maybe add a toggle to allow the pathfinding to use flight. Baritone will likely replace this option in the future though.

**Comment by kittenvr** [comment]
> That should be really easy to do. I will work on that within the next couple of days.
> 
> I will try to incorporate some more complex pathfinding so it doesn't necessarily need to use flight, and maybe add a toggle to allow the pathfinding to use flight. Baritone will likely replace this option in the future though.

oh thanks

**Comment by kittenvr** [comment]
> That should be really easy to do. I will work on that within the next couple of days.
> 
> I will try to incorporate some more complex pathfinding so it doesn't necessarily need to use flight, and maybe add a toggle to allow the pathfinding to use flight. Baritone will likely replace this option in the future though.

why will baritone replace it cant you just have them both?

**Comment by coltonk9043** [comment]
I could, but what would be the point of a custom pathfinder if I could just rely on Baritone to do it?

**Comment by kittenvr** [comment]
> I could, but what would be the point of a custom pathfinder if I could just rely on Baritone to do it?

baritone cant fly

**Comment by coltonk9043** [comment]
No, but the Client can. I'm sure I can manipulate Baritone to do what I need it to.

**Comment by kittenvr** [comment]
> No, but the Client can. I'm sure I can manipulate Baritone to do what I need it to.

are you saying you can make a version of baritone that uses flight?

**Comment by coltonk9043** [comment]
> > No, but the Client can. I'm sure I can manipulate Baritone to do what I need it to.
> 
> 
> 
> are you saying you can make a version of baritone that uses flight?
> 
> 

I'm not really sure. If Baritone has a creative function, I'm sure I can trick it to think you're in Creative mode

**Comment by coltonk9043** [comment]
Closing. Added in e3c0fb6

**Comment by kittenvr** [comment]
Does it work in boat?

**Comment by coltonk9043** [comment]
No rn, I can add that tonight.
