### ISSUE TITLE
ADD TRIGGERBOT

### ISSUE THREAD

**Issue by mroep** [coltonk9043/Aoba-MC-Hacked-Client#5]
can you add trigger bot??

**Comment by coltonk9043** [comment]
I can! As soon as exams are finished I will be consistently working on this and other projects.

**Comment by mroep** [comment]
Really appreciate it so much

**Comment by JAVAHTML1** [comment]
Please work on this.

**Comment by coltonk9043** [comment]
Triggerbot is now up on the 1.3A release with 1.20 Support. If there are any issues or features you'd like, please let me know!
